---
- name: Update apt on DB Servers
  become: yes
  apt:
    name: ["apt"]
    state: latest

- name: Install software/packages on DB Servers
  become: yes
  ansible.builtin.apt:
    name: ['python3-dev', 'python3-setuptools', 'python3-pip']
    state: latest
    update_cache: yes
#  with_items: "{{ groups['DB_SERVER_NODES'] }}"
#  when: ansible_distribution == "Ubuntu"

- name: Update pip on DB Servers
  pip:
    name: ['pip', 'openstacksdk']
    state: latest

- name: Install nginx on the servers
  become: true
  apt:
    state: present
    name: ["nginx"]
    update_cache: true
  #with_items: "{{ groups['DB_SERVER_NODES'] }}"
  #when: item.instance_name != "AppServer"