---
- name: Update apt
  become: yes
  apt:
    name: ["apt"]
    state: latest

- name: Install pip
  become: yes
  ansible.builtin.apt:
    name: ['python3-dev', 'python3-setuptools', 'python3-pip']
    state: latest
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: Update pip
  pip:
    name: ['pip', 'openstacksdk']
    state: latest