---

- include: create_couchdb_container.yaml

- name: Cluster setup
  uri:
    url: http://{{ groups['DB_MASTER_NODE'][0] }}:5984/_cluster_setup
    user: '{{ user }}'
    password: '{{ pass }}'
    method: POST
    body: "{
            \"action\": \"enable_cluster\", \"bind_address\": \"0.0.0.0\",
            \"username\": \"{{ user }}\", \"password\": \"{{ pass }}\", \"port\": \"5984\",
            \"remote_node\": \"{{ ansible_ssh_host }}\", \"node_count\": \"{{ nnodes }}\",
            \"remote_current_user\": \"{{ user }}\", \"remote_current_password\": \"{{ pass }}\"
            }"
    body_format: json
    status_code: [200, 201]
    return_content: true
    headers:
      Content-Type: "application/json"
    force_basic_auth: yes
#  when: ansible_ssh_host != masternode
  with_items: "{{ groups['DB_SERVER_NODES'] }}"
  when: item not in  groups['DB_MASTER_NODE']
  register: setup

- ansible.builtin.debug:
    msg: '{{ setup }}'
  when: setup is defined

- name: Adding node
  uri:
    url: http://{{ groups['DB_MASTER_NODE'][0] }}:5984/_cluster_setup
    user: '{{ user }}'
    password: '{{ pass }}'
    method: POST
    body: "{
              \"action\": \"add_node\", \"host\":\"{{ ansible_ssh_host }}\",\
              \"port\": \"5984\", \"username\": \"{{ user }}\", \"password\":\"{{ pass }}\"
            }"
    body_format: json
    status_code: [200, 201]
    return_content: true
    headers:
      Content-Type: "application/json"
    force_basic_auth: yes
  when: ansible_ssh_host not in groups['DB_MASTER_NODE']
#  with_items: "{{ groups['DB_SERVER_NODES'] }}"
#  when: item not in groups['DB_MASTER_NODE']
  register: node

- ansible.builtin.debug:
    msg: '{{ node }}'
  when: node is defined

# Configure the cluster
- include: cluster_configuration.yaml

# create databases on the new db nodes
- include: add_databases.yaml

# mount the data volumes
- include: mount_volumes.yaml

# copy files from localhost to remote node and load
- include: load_data.yaml