---
# Team 14 - Melbourne

# Kranthi Kumar Kommuri 1049507
# James Ng 1316315
# Emmanuel Pinca 1080088
# Matteo Rossi 1222468
# Thanadol Ultarnpatumros 1323866

# Install dependencies on the host

- name: Install pip
  become: yes
  ansible.builtin.apt:
    name: ['python3-dev','python3-setuptools','python3-pip']
    state: latest
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: Update pip
  ansible.builtin.pip:
    name: ['pip','openstacksdk']
    state: latest
