# Team 14 - Melbourne
#
# Kranthi Kumar Kommuri 1049507
# James Ng 1316315
# Emmanuel Pinca 1080088
# Matteo Rossi 1222468
# Thanadol Ultarnpatumros 1323866

- hosts: db1
  vars_files:
    - variables/vars.yaml
  gather_facts: true

  roles:
    - role: common
    - role: docker
    - role: couchdb

- hosts: db2
  vars_files:
    - variables/vars.yaml
  gather_facts: true

  roles:
    - role: common
    - role: docker
    - role: couchdb

- hosts: db3
  vars_files:
    - variables/vars.yaml
  gather_facts: true

  roles:
    - role: common
    - role: docker
    - role: couchdb

- hosts: db1
  vars_files:
    - variables/vars.yaml
  gather_facts: true

  roles:
    - role: cluster-configuration

- hosts: db2
  vars_files:
    - variables/vars.yaml
  gather_facts: true

  roles:
    - role: cluster-configuration

- hosts: db3
  vars_files:
    - variables/vars.yaml
  gather_facts: true

  roles:
    - role: cluster-configuration