---
# Mount the volumes before copying files
- include: mount_volumes.yaml 

- name: Install pip
  become: yes
  ansible.builtin.apt:
    name: ['python3-dev','python3-setuptools','python3-pip']
    state: latest
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: Update pip and install dependencies
  ansible.builtin.pip:
    name: ['pip','folium','flask','waitress','pandas','numpy','shapely','geopandas','couchdb','flask_wtf','wtforms','matplotlib']
    state: latest

# Copy files from localhost to the remote Application Server
### Not sure if needed
- name: Copy the python script from localhost to remote server
  ansible.builtin.copy:
     dest: /frontend
     src: ../files/app.py
     backup: no
     owner: ubuntu
     mode: '0644'

- name: Copy the html from localhost to remote server
  ansible.builtin.copy:
     dest: /frontend/templates
     src: ../files/index.html
     backup: no
     owner: ubuntu
     mode: '0644'

- name: Copy the vic suburb data from localhost to remote server
  ansible.builtin.copy:
     dest: /frontend/localities
     src: ../files/vic.shp
     backup: no
     owner: ubuntu
     mode: '0644'

- name: Run frontend python script
  shell: |
    python3 /frontend/app.py 172.26.134.187