---
# Mount the volumes before copying files
- include: mount_volumes.yaml 

- name: Install pip
  become: yes
  ansible.builtin.apt:
    name: ['python3-dev','python3-setuptools','python3-pip']
    state: latest
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: Update pip and install dependencies
  ansible.builtin.pip:
    name: ['pip','folium','flask','waitress','pandas','numpy','shapely','geopandas','couchdb','flask_wtf','wtforms','matplotlib']
    state: latest

# Copy files from localhost to the remote Application Server
- name: Copy the data files from localhost to remote server
  ansible.builtin.copy:
     dest: /data3
     src: ../files/testfile.txt
     backup: no
     owner: ubuntu
     mode: '0644'